name: PR Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    name: Label Pull Request
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auto-label based on files changed
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Label by PR author
        uses: actions/github-script@v7
        with:
          script: |
            const author = context.payload.pull_request.user.login;
            
            // Define allowed users who can push directly
            const allowedUsers = ['subham2023', 'sidhyaashu'];
            
            // Define restricted users who need approval
            const restrictedUsers = ['Abhishek-Royy', 'Sayandip05'];
            
            let labels = [];
            
            if (allowedUsers.includes(author)) {
              labels.push('trusted-contributor');
            } else if (restrictedUsers.includes(author)) {
              labels.push('needs-approval');
            }
            
            // Add size labels based on changes
            const changedFiles = context.payload.pull_request.changed_files;
            if (changedFiles < 10) {
              labels.push('size/small');
            } else if (changedFiles < 30) {
              labels.push('size/medium');
            } else {
              labels.push('size/large');
            }
            
            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: labels
              });
            }

      - name: Request review from code owners
        uses: actions/github-script@v7
        if: contains(github.event.pull_request.user.login, 'Abhishek-Royy') || contains(github.event.pull_request.user.login, 'Sayandip05')
        with:
          script: |
            // Automatically request review from code owners for restricted users
            const codeOwners = ['subham2023', 'sidhyaashu'];
            
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: codeOwners
            });
            
            // Add a comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: '👋 Thank you for your contribution! This PR requires approval from code owners before it can be merged. Reviews have been requested automatically.'
            });

